name = "bebig-backend"
main = "src/index.ts"
compatibility_date = "2024-11-12"

[vars]
# Add environment variables if needed

[[kv_namespaces]]
binding = "SESSIONS"
id = "f1e89a02b6264c2e9cf57b6adb46c010"

[[d1_databases]]
binding = "DB"
database_name = "bebig-db"
database_id = "f93adfcc-7247-462c-9d61-3e759dba2244"
migrations_dir = "migrations"

[ai]
binding = "AI"
